### 미니 테스트 <hr>

In [4]:
import torch
import numpy as np
import pandas as pd
import random

1. 화면상에서 Pytorch에서 데이터를 저장하는 단위는 (Tensor)입니다.

2. 문제 1에 해당하는 것의 특징을 간략히 설명하세요.

3. int8, int16, int32, int64, uint8, Long

4. Pytorch에 논리형 데이터로 저장 후 속성을 출력하는 코드를 작성하세요.

In [ ]:
data = [10, -5, 1.4, 7, 0, -1, 0]
t = torch.tensor(data, dtype = bool)
print(t.dtype)

torch.bool

5. 10개의 0으로 구성된 데이터를 2차원으로 저장하는 코드를 작성하세요.

In [10]:
t = torch.zeros((2, 5), dtype = torch.float32)
print(t)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


6. 5개의 1로 구성된 데이터가 2차원 텐서의 대각선에 저장되는 코드를 작성하세요. 

In [ ]:
t = torch.eye(5)
print(t)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


7. 문제 5에서 저장된 형태가 동일하지만 값이 3이 저장된 코드를 작성하세요.

In [ ]:
t = torch.rand(2, 5)
t = 3*torch.ones_like(t)
print(t)

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])


8. ndarray 데이터를 Pytorch에 저장하는 코드를 작성하세요.
- 데이터  :1 ~ 100 범위에서 7의 배수
- 데이터 타입 : float32
- 생성 방식 : 공유

In [ ]:
data = np.arange(1, 101, 7)

t = torch.from_numpy(data)
t = t.type(torch.float32)
print(t)

t = torch.as_tensor(data)
t = t.type(torch.float32)
print(t)

tensor([ 1.,  8., 15., 22., 29., 36., 43., 50., 57., 64., 71., 78., 85., 92.,
        99.])
tensor([ 1.,  8., 15., 22., 29., 36., 43., 50., 57., 64., 71., 78., 85., 92.,
        99.])
torch.float32


9. 아래 조건에 맞는 데이터를 Pytorch에 저장하는 코드를 작성하세요.
- 이미지 파일 : flower.jpg 파일
- 이미지 크기 : 120 x 80
- 데이터 타입 : int8
- 데이터 : 임의의 값

10. 아래 조건에 맞도록 코드를 작성하세요.
- 데이터 : 임의의 정수 10개

In [ ]:
# (1) 1D으로 저장
data = []
for i in range(10):
    data.append(random.randint(1, 10))
t = torch.tensor(data)
print(t)

tensor([10,  1,  5,  8, 10,  5,  4,  8,  6,  4])


In [ ]:
# (2) (1)에서 저장된 데이터를 요소 수 변경 없이 3D로 변환

t = t.unsqueeze(dim = 0)
t = t.unsqueeze(dim = 0)
print(t)

tensor([[[10,  1,  5,  8, 10,  5,  4,  8,  6,  4]]])


In [ ]:
# (3) (2)에서 저장된 데이터의 차원 중 2개를 변경한 3D로 변환
tt = t.transpose(0, 2)
print(tt)

tensor([[[10]],

        [[ 1]],

        [[ 5]],

        [[ 8]],

        [[10]],

        [[ 5]],

        [[ 4]],

        [[ 8]],

        [[ 6]],

        [[ 4]]])


In [ ]:
# (4) (2)에서 저장된 데이터의 3개 차원 모두 변경한 3D로 변환
t = t.permute(2, 1, 0)
print(t)

tensor([[[10]],

        [[ 1]],

        [[ 5]],

        [[ 8]],

        [[10]],

        [[ 5]],

        [[ 4]],

        [[ 8]],

        [[ 6]],

        [[ 4]]])


11. 아래 조건에 맞도록 코드를 작성하세요.
- 데이터
    - 국어 80, 70, 80
    - 영어 70, 100, 80
    - 수학 99, 88, 77

In [ ]:
# (1) 위에 데이터를 저장
data = pd.DataFrame({'국어' : [90, 70, 80], '영어' : [70, 100, 80], '수학' : [99, 88, 77]})
print(data)

   국어   영어  수학
0  90   70  99
1  70  100  88
2  80   80  77


In [ ]:
# (2) 과목별 합계, 평균, 최고점수 출력
print(data.sum())
print(data.mean())
print(data.max())

국어    240
영어    250
수학    264
dtype: int64
국어    80.000000
영어    83.333333
수학    88.000000
dtype: float64
국어     90
영어    100
수학     99
dtype: int64


In [ ]:
# (3) 한 사람의 국어, 영어, 수학 점수 합계, 평균, 최고점수 출력
print(data.sum(axis = 1))
print(data.mean(axis = 1))
print(data.max(axis = 1))

0    259
1    258
2    237
dtype: int64
0    86.333333
1    86.000000
2    79.000000
dtype: float64
0     99
1    100
2     80
dtype: int64


12. 아래 조건에 맞도록 코드를 작성하세요.
- 데이터1
    - 국어 90, 70, 80
    - 영어 70, 100, 80
    - 수학 99, 88, 77
- 데이터2
    - 0.5, 0.2, 0.7

In [6]:
# (1) 위에 데이터를 저장
data1 = pd.DataFrame({'국어' : [90, 70, 80], '영어' : [70, 100, 80], '수학' : [99, 88, 77]})
data2 = np.array([0.5, 0.2, 0.7])
data2

array([0.5, 0.2, 0.7])

In [8]:
# (2) 데이터1과 데이터2의 사칙연산 결과
data1 = np.array(data1)
t1 = torch.tensor(data1, dtype = torch.float64)
t2 = torch.tensor(data2)
add = t1.add(t2)
matmul = t1.matmul(t2)
print(add, matmul)


tensor([[ 90.5000,  70.2000,  99.7000],
        [ 70.5000, 100.2000,  88.7000],
        [ 80.5000,  80.2000,  77.7000]], dtype=torch.float64) tensor([128.3000, 116.6000, 109.9000], dtype=torch.float64)
