In [18]:
import torch
import torch.nn as nn
from torchinfo import summary

In [20]:
class Net(nn.Module):
    
    # 모델 구성 요소 생성 및 구조 설정
    def __init__(self):
        super(Net, self).__init__()  # super()로 써도 된다. 즉 괄호 안에 Net, self 생략가능

        self.layer1 = nn.Linear(8, 4)
        self.layer2 = nn.Linear(4, 2)
        self.drop = nn.Dropout(0.5)
        self.layer3 = nn.Linear(2, 1)

    # 순방향 학습 진행 함수
    def forward(self, x):
        return self.layer3(self.drop(self.layer2(self.layer1(x))))

In [21]:
# 모델 인스턴스 생성
model = Net()

In [22]:
# 모델 인스턴스 속성 확인
# 모델의 특정 층 추출
model.layer1.weight, model.layer1.bias

(Parameter containing:
 tensor([[-0.1691,  0.2798, -0.0950, -0.1396, -0.1234, -0.3406,  0.0381, -0.2404],
         [ 0.0901,  0.3532, -0.0166,  0.1572,  0.2618, -0.1659,  0.0367, -0.1298],
         [-0.3021, -0.3519,  0.2821,  0.3363, -0.2424, -0.2845,  0.3389, -0.2313],
         [-0.2973,  0.2145,  0.2701, -0.2435,  0.2934,  0.2751,  0.2423,  0.1479]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.0989,  0.2592, -0.0798, -0.2185], requires_grad=True))

In [23]:
for param in model.parameters():
    print(param, end = '\n\n')

Parameter containing:
tensor([[-0.1691,  0.2798, -0.0950, -0.1396, -0.1234, -0.3406,  0.0381, -0.2404],
        [ 0.0901,  0.3532, -0.0166,  0.1572,  0.2618, -0.1659,  0.0367, -0.1298],
        [-0.3021, -0.3519,  0.2821,  0.3363, -0.2424, -0.2845,  0.3389, -0.2313],
        [-0.2973,  0.2145,  0.2701, -0.2435,  0.2934,  0.2751,  0.2423,  0.1479]],
       requires_grad=True)

Parameter containing:
tensor([-0.0989,  0.2592, -0.0798, -0.2185], requires_grad=True)

Parameter containing:
tensor([[-0.3600, -0.0955,  0.2970, -0.0391],
        [-0.3290, -0.0510,  0.3208, -0.3411]], requires_grad=True)

Parameter containing:
tensor([0.1889, 0.0932], requires_grad=True)

Parameter containing:
tensor([[0.3480, 0.2892]], requires_grad=True)

Parameter containing:
tensor([-0.4298], requires_grad=True)



In [24]:
# 모델의 각 층별 w, b 텐서 정보 확인
for param in model.named_parameters():
    print(param, end = '\n\n')

('layer1.weight', Parameter containing:
tensor([[-0.1691,  0.2798, -0.0950, -0.1396, -0.1234, -0.3406,  0.0381, -0.2404],
        [ 0.0901,  0.3532, -0.0166,  0.1572,  0.2618, -0.1659,  0.0367, -0.1298],
        [-0.3021, -0.3519,  0.2821,  0.3363, -0.2424, -0.2845,  0.3389, -0.2313],
        [-0.2973,  0.2145,  0.2701, -0.2435,  0.2934,  0.2751,  0.2423,  0.1479]],
       requires_grad=True))

('layer1.bias', Parameter containing:
tensor([-0.0989,  0.2592, -0.0798, -0.2185], requires_grad=True))

('layer2.weight', Parameter containing:
tensor([[-0.3600, -0.0955,  0.2970, -0.0391],
        [-0.3290, -0.0510,  0.3208, -0.3411]], requires_grad=True))

('layer2.bias', Parameter containing:
tensor([0.1889, 0.0932], requires_grad=True))

('layer3.weight', Parameter containing:
tensor([[0.3480, 0.2892]], requires_grad=True))

('layer3.bias', Parameter containing:
tensor([-0.4298], requires_grad=True))



In [25]:
# 모델을 구성하는 모든 Layer 가져오기
for child in model.children():
    print(child, end = '\n\n')

# 이름까지 같이 출력
for child in model.named_children():
    print(child, end = '\n\n')

Linear(in_features=8, out_features=4, bias=True)

Linear(in_features=4, out_features=2, bias=True)

Dropout(p=0.5, inplace=False)

Linear(in_features=2, out_features=1, bias=True)

('layer1', Linear(in_features=8, out_features=4, bias=True))

('layer2', Linear(in_features=4, out_features=2, bias=True))

('drop', Dropout(p=0.5, inplace=False))

('layer3', Linear(in_features=2, out_features=1, bias=True))



- Layer의 가중치 설정

In [26]:
# 세비어 알고리즘의 가중치 초기화
nn.init.xavier_uniform_(model.layer1.weight)  # inplace = True가 디폴트

Parameter containing:
tensor([[ 0.5895, -0.0710, -0.7026,  0.2660, -0.0344, -0.1886, -0.1574, -0.5267],
        [-0.7016, -0.4249,  0.1510,  0.5589, -0.2270,  0.2366,  0.5266, -0.5480],
        [ 0.0083,  0.1225, -0.3105,  0.2836,  0.5705, -0.5360, -0.3386,  0.6806],
        [-0.0921, -0.6355,  0.6413,  0.1715,  0.5771, -0.3374, -0.3321, -0.4997]],
       requires_grad=True)

In [27]:
# 헤 알고리즘의 가중치 초기화
nn.init.kaiming_normal_(model.layer2.weight)

Parameter containing:
tensor([[-0.6015, -0.2776,  0.1005,  0.2169],
        [ 0.0891, -0.6482, -0.9764, -0.1793]], requires_grad=True)

In [31]:
# 모델 저장
torch.save(model, '../model/my_model.pt')

In [34]:
# 저장된 모델 불러오기
mymodel = torch.load('../model/my_model.pt')
mymodel

Net(
  (layer1): Linear(in_features=8, out_features=4, bias=True)
  (layer2): Linear(in_features=4, out_features=2, bias=True)
  (drop): Dropout(p=0.5, inplace=False)
  (layer3): Linear(in_features=2, out_features=1, bias=True)
)

In [28]:
# 모델 인스턴스 생성
model = Net()

print(model)

summary(model)

Net(
  (layer1): Linear(in_features=8, out_features=4, bias=True)
  (layer2): Linear(in_features=4, out_features=2, bias=True)
  (drop): Dropout(p=0.5, inplace=False)
  (layer3): Linear(in_features=2, out_features=1, bias=True)
)


Layer (type:depth-idx)                   Param #
Net                                      --
├─Linear: 1-1                            36
├─Linear: 1-2                            10
├─Dropout: 1-3                           --
├─Linear: 1-4                            3
Total params: 49
Trainable params: 49
Non-trainable params: 0