In [1]:
import torch
import torch.nn.functional as F
import torch.optim as optim

In [18]:
a = torch.IntTensor(10)
b = torch.tensor(2., requires_grad = True)

In [19]:
print('a tensor', a.shape, a.ndim, a.requires_grad, a.grad, a.is_leaf, a.grad_fn)
print('b tensor', b.shape, b.ndim, b.requires_grad, b.grad, b.is_leaf, b.grad_fn)

a tensor torch.Size([10]) 1 False None True None
b tensor torch.Size([]) 0 True None True None


In [20]:
c = a.mul(b)

In [21]:
print('c tensor', c.shape, c.ndim, c.requires_grad, c.grad, c.is_leaf, c.grad_fn)

c tensor torch.Size([10]) 1 True None False <MulBackward0 object at 0x0000028817D52340>


C:\Users\user\AppData\Local\Temp\ipykernel_33860\2174180184.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\b\abs_6fueooay2f\croot\pytorch-select_1707342446212\work\build\aten\src\ATen/core/TensorBody.h:494.)
  print('c tensor', c.shape, c.ndim, c.requires_grad, c.grad, c.is_leaf, c.grad_fn)


In [22]:
b.backward()

In [23]:
sgd = optim.SGD

In [25]:
x1 = torch.ones(5)  # input tensor
y1 = torch.zeros(3)  # expected tensor

w1 = torch.randn(5, 3, requires_grad = True)
b1 = torch.randn(3, requires_grad = True)
z1 = torch.matmul(x1, w1) + b

y2 = torch.zeros(1)  # expected output
w2 = torch.randn(3, requires_grad = True)
b2 = torch.randn(1, requires_grad = True)
z2 = torch.matmul(z1, w2) + b2

loss = torch.nn.functional.binary_cross_entropy_with_logits(z2, y2)

In [26]:
print('x tensor', x1.shape, x1.ndim, x1.requires_grad, x1.grad, x1.is_leaf, x1.grad_fn)
print('x tensor', y1.shape, y1.ndim, y1.requires_grad, y1.grad, y1.is_leaf, y1.grad_fn)

print('w1 tensor', w1.shape, w1.ndim, w1.requires_grad, w1.grad, w1.is_leaf, w1.grad_fn)
print('b1 tensor', b1.shape, b1.ndim, b1.requires_grad, b1.grad, b1.is_leaf, b1.grad_fn)
print('z1 tensor', z1.shape, z1.ndim, z1.requires_grad, z1.grad, z1.is_leaf, z1.grad_fn)

print('w2 tensor', w2.shape, w2.ndim, w2.requires_grad, w2.grad, w2.is_leaf, w2.grad_fn)
print('b2 tensor', b2.shape, b2.ndim, b2.requires_grad, b2.grad, b2.is_leaf, b2.grad_fn)
print('z2 tensor', z2.shape, z2.ndim, z2.requires_grad, z2.grad, z2.is_leaf, z2.grad_fn)


x tensor torch.Size([5]) 1 False None True None
x tensor torch.Size([3]) 1 False None True None
w1 tensor torch.Size([5, 3]) 2 True None True None
b1 tensor torch.Size([3]) 1 True None True None
z1 tensor torch.Size([3]) 1 True None False <AddBackward0 object at 0x0000028817DA6970>
w2 tensor torch.Size([3]) 1 True None True None
b2 tensor torch.Size([1]) 1 True None True None
z2 tensor torch.Size([1]) 1 True None False <AddBackward0 object at 0x0000028817DA6FA0>


C:\Users\user\AppData\Local\Temp\ipykernel_33860\2990915066.py:6: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\b\abs_6fueooay2f\croot\pytorch-select_1707342446212\work\build\aten\src\ATen/core/TensorBody.h:494.)
  print('z1 tensor', z1.shape, z1.ndim, z1.requires_grad, z1.grad, z1.is_leaf, z1.grad_fn)
C:\Users\user\AppData\Local\Temp\ipykernel_33860\2990915066.py:10: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a no

In [27]:
print(w2, w2.grad)
print(b2, b2.grad)
print(w1, w1.grad)
print(b1, b1.grad)

tensor([-1.4161, -1.1274, -0.3324], requires_grad=True) None
tensor([0.7247], requires_grad=True) None
tensor([[-0.8236,  1.7063,  0.4701],
        [ 0.8280,  0.5049, -0.4785],
        [ 0.0085, -0.0646, -0.5571],
        [ 2.0278,  0.7315, -1.5269],
        [-0.4506,  0.8663, -1.1500]], requires_grad=True) None
tensor([ 0.2837, -0.0395,  1.4867], requires_grad=True) None


In [28]:
loss.backward()

In [29]:
print(w2, w2.grad)
print(b2, b2.grad)
print(w1, w1.grad)
print(b1, b1.grad)

tensor([-1.4161, -1.1274, -0.3324], requires_grad=True) tensor([ 1.0680e-04,  1.7088e-04, -3.6961e-05])
tensor([0.7247], requires_grad=True) tensor([2.9747e-05])
tensor([[-0.8236,  1.7063,  0.4701],
        [ 0.8280,  0.5049, -0.4785],
        [ 0.0085, -0.0646, -0.5571],
        [ 2.0278,  0.7315, -1.5269],
        [-0.4506,  0.8663, -1.1500]], requires_grad=True) tensor([[-4.2124e-05, -3.3538e-05, -9.8889e-06],
        [-4.2124e-05, -3.3538e-05, -9.8889e-06],
        [-4.2124e-05, -3.3538e-05, -9.8889e-06],
        [-4.2124e-05, -3.3538e-05, -9.8889e-06],
        [-4.2124e-05, -3.3538e-05, -9.8889e-06]])
tensor([ 0.2837, -0.0395,  1.4867], requires_grad=True) None
