### 선형 모델 동작 살펴보기
- nn.Linear 클래스
- y = wx + b 공식으로 동작하는 선형회귀모델

In [25]:
### ===> 모듈 로딩
import torch
import torch.nn as nn
import torch.nn.functional as F

In [17]:
### ===> 테스트용 임의의 데이터
data = torch.FloatTensor([[8, 9], [6, 6], [3, 4]])
target = torch.LongTensor([[17], [12]])

data.shape, target.shape

(torch.Size([3, 2]), torch.Size([2, 1]))

In [18]:
### 선형모델 인스턴스 생성 ==> 가 입력 데이터의 피처 갯수, 각출력 데이터의 피처 개수
linear = nn.Linear(2, 1)

In [19]:
### ===> 학습
output = linear(data)

print(f'[학습 결과]\n{output.shape}\n{output}')


[학습 결과]
torch.Size([3, 1])
tensor([[6.1452],
        [4.1251],
        [2.4272]], grad_fn=<AddmmBackward0>)


In [20]:
### ===> 모델 파라미터 w, b
linear.weight

Parameter containing:
tensor([[0.2107, 0.5329]], requires_grad=True)

In [21]:
linear.bias

Parameter containing:
tensor([-0.3366], requires_grad=True)

In [22]:
# 아래 두 결과는 동일
for i, value in enumerate(output.data):
    print(f'[{i}] {value.item()}')

print()
for i, value in enumerate(output.data):
    print(f'[{i}] {output.data[i].item()}')

[0] 6.145223617553711
[1] 4.125058174133301
[2] 2.427175521850586

[0] 6.145223617553711
[1] 4.125058174133301
[2] 2.427175521850586


In [23]:
data

tensor([[8., 9.],
        [6., 6.],
        [3., 4.]])

In [24]:
### 선형식
w1 = linear.weight[0][0].item()
w2 = linear.weight[0][1].item()
b = linear.bias[0].item()

y = w1*8. + w2*9. + b

print(y)

6.145223319530487


#### Linear 결과와 활성화 함수
- 인공신경망에서 전결합층에 해당하는 Linear 모델에 AF함수 적용

In [26]:
### ===> 활성화함수(AF) 적용
### sigmoid함수 => 0.1 ~ 1.0 범위의 값으로 반환 

af = F.sigmoid(output)
print(af)

tensor([[0.9979],
        [0.9841],
        [0.9189]], grad_fn=<SigmoidBackward0>)


In [27]:
### relu 함수 => 값 > 0 : 그대로, 값 <= 0 : 0 반환
af = F.relu(output)
print(af)

tensor([[6.1452],
        [4.1251],
        [2.4272]], grad_fn=<ReluBackward0>)
