### softmax() 함수, sigmoide() 함수 <hr>
- sigmoid() : y = wx + b 결과 1개를 전달 ===> 반환 : 0.0 ~ 1.0 사이값으로 변환 ==> 이진분류
- softmax() : y = wx + b 결과 1개를 전달 ===> 반환 : 결과값의 합이 1.0이 되도록 변환 ==> 다중분류

In [2]:
# 모듈로딩
import torch                     # 파이토치 기본 모듈로 텐서 및 기본 함수들
import torch.nn.functional as F  # 파이토치 인공신경망 관련 함수들

In [4]:
# 임의 데이터 생성
data1 = torch.tensor([1, 2, 1, 2, 1])
data1.shape

torch.Size([5])

In [5]:
F.sigmoid(data1)

tensor([0.7311, 0.8808, 0.7311, 0.8808, 0.7311])

In [6]:
data2 = data1.unsqueeze(dim = 0)
data2.shape, data2

(torch.Size([1, 5]), tensor([[1, 2, 1, 2, 1]]))

In [7]:
input = torch.randn(2, 3)
input

tensor([[ 1.4961,  1.5988,  1.5212],
        [-0.1930,  0.8600, -1.0949]])

In [9]:
output = F.softmax(input)
output

C:\Users\user\AppData\Local\Temp\ipykernel_8732\3352805213.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output = F.softmax(input)


tensor([[0.3191, 0.3536, 0.3272],
        [0.2341, 0.6709, 0.0950]])

In [10]:
output.sum(axis = 1)

tensor([1., 1.])

In [13]:
output.max(dim = 1)[1][0].item()

1

In [14]:
output.argmax(dim  = 1)

tensor([1, 1])