### 인공신경망 모델 클래스 만들기 <hr>
- 부모 클래스 : nn.Module 상속 받음
- 필수 오버라이딩 메서드 : __init__(), forward()

[1] 모듈로딩 <hr>

In [1]:
import torch
import torch.nn as nn

In [11]:
# 로지스틱회귀 모델 클래스 생성
# - Linear + Sigmoid

class LogicsticLinear(nn.Module):
    
    # 모델 구조 설정
    def __init__(self, in_, out_):
        super().__init__()
        self.layer1 = nn.Linear(in_, 10)
        self.sigmoid1 = nn.Sigmoid()
        self.layer2 = nn.Linear(10, out_)
        self.sigmoid2 = nn.Sigmoid()
    
    # 순방향 학습 진행 콜백함수
    def forward(self, x):
        y = self.layer1(x)
        z = self.sigmoid1(y)
        y = self.layer2(z)
        z = self.sigmoid2(y)
        return z

In [14]:
# 모델 인스턴스 생성
ll = LogicsticLinear(784, 10)

print(f'모델 구조 확인 ====\n {ll}')

모델 구조 확인 ====
 LogicsticLinear(
  (layer1): Linear(in_features=784, out_features=10, bias=True)
  (sigmoid1): Sigmoid()
  (layer2): Linear(in_features=10, out_features=10, bias=True)
  (sigmoid2): Sigmoid()
)


In [15]:
print(f'모델구성 w, b ====')
for param in ll.parameters(): print(param)

모델구성 w, b ====
Parameter containing:
tensor([[-0.0021,  0.0098,  0.0021,  ..., -0.0219,  0.0232, -0.0291],
        [ 0.0306, -0.0032, -0.0153,  ..., -0.0180,  0.0136, -0.0135],
        [ 0.0197, -0.0291,  0.0226,  ..., -0.0008, -0.0272, -0.0237],
        ...,
        [-0.0116, -0.0122, -0.0273,  ...,  0.0168, -0.0102, -0.0105],
        [-0.0353,  0.0224,  0.0086,  ...,  0.0206,  0.0069,  0.0276],
        [-0.0124, -0.0263, -0.0262,  ...,  0.0298,  0.0017, -0.0145]],
       requires_grad=True)
Parameter containing:
tensor([-0.0210, -0.0098, -0.0051,  0.0086,  0.0121, -0.0015,  0.0166, -0.0185,
        -0.0176,  0.0221], requires_grad=True)
Parameter containing:
tensor([[-0.2675,  0.0507,  0.0864, -0.1678, -0.0198,  0.0354, -0.0487, -0.1522,
         -0.2278, -0.1811],
        [ 0.2178,  0.1710, -0.2421,  0.1686,  0.0315, -0.2726,  0.1169,  0.0988,
          0.0312,  0.1813],
        [-0.1087, -0.2663,  0.3039,  0.1347, -0.0455,  0.1210,  0.2383,  0.0505,
          0.2887,  0.0295],
    

In [16]:
ll.parameters()

<generator object Module.parameters at 0x0000019653494B30>