### 텐서(Tensor) 살펴보기
- Pytorch에서 데이터 저장 자료형
- 모델 입력(input), 출력(output) 데이터 형태

- 모듈 로딩

In [122]:
import torch

- Tensor 속성 관련 함수

In [123]:
# 매개변수 : 텐서 인스턴스, 텐서 변수명 
def print_attribute(tensor, name):
    print(f'[ Tensor {name}\'s Attribute ]')
    print(f'- tensor.shape : {tensor.shape}')
    print(f'- tensor.ndim : {tensor.ndim}D')
    print(f'- tensor.dtype : {tensor.dtype}')
    print(f'- tensor.device : {tensor.device}')
    print(f'- tensor.requires_grad : {tensor.requires_grad}')
    print(f'- tensor.data \n{tensor.data}')

- Tensor 생성 (1) 특정 데이터 타입의 텐서 생성
    * 타입별 텐서 클래스 생성자 활용
    * 예) IntTensor(), FloatTensor(), BoolTensor()

In [155]:
# 정수 타입 텐서 생성 => 실수를 넣어도 정수로 자동 변환되나 데이터 손실 발생할 수 있다.
t1 = torch.IntTensor([10])
t2 = torch.IntTensor([10, 20])

# 부울 타입 텐서 생성 => 부울로 자동 변환
t3 = torch.BoolTensor([1, 1, 0, -1])

# 실수 타입 텐서 생성 => 정수를 넣어도 실수로 자동 변환
t4 = torch.FloatTensor([10, 20])

In [156]:
print_attribute(t1, 't1')
print_attribute(t2, 't2')
print_attribute(t3, 't3')
print_attribute(t4, 't4')

[ Tensor t1's Attribute ]
- tensor.shape : torch.Size([1])
- tensor.ndim : 1D
- tensor.dtype : torch.int32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([10], dtype=torch.int32)
[ Tensor t2's Attribute ]
- tensor.shape : torch.Size([2])
- tensor.ndim : 1D
- tensor.dtype : torch.int32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([10, 20], dtype=torch.int32)
[ Tensor t3's Attribute ]
- tensor.shape : torch.Size([4])
- tensor.ndim : 1D
- tensor.dtype : torch.bool
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([ True,  True, False,  True])
[ Tensor t4's Attribute ]
- tensor.shape : torch.Size([2])
- tensor.ndim : 1D
- tensor.dtype : torch.float32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([10., 20.])


- Tensor 생성 (2) 원하는 값으로 텐서 생성 => torch.tensor()

In [157]:
t1 = torch.tensor(10)  # scalar 데이터, int64
t2 = torch.tensor(10.)  # scalar 데이터, float32

In [158]:
print_attribute(t1, 't1')
print_attribute(t2, 't2')

[ Tensor t1's Attribute ]
- tensor.shape : torch.Size([])
- tensor.ndim : 0D
- tensor.dtype : torch.int64
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
10
[ Tensor t2's Attribute ]
- tensor.shape : torch.Size([])
- tensor.ndim : 0D
- tensor.dtype : torch.float32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
10.0


In [128]:
# dtype 매개변수에 원하는 데이터 타입을 지정할 수 있다.
t1 = torch.tensor(10., dtype = torch.int32)  # scalar 데이터, int32
print_attribute(t1, 't1')

[ Tensor t1's Attribute ]
- tensor.shape : torch.Size([])
- tensor.ndim : 0D
- tensor.dtype : torch.int32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
10


C:\Users\user\AppData\Local\Temp\ipykernel_6716\1966216171.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t1 = torch.tensor(10., dtype = torch.int32)  # scalar 데이터, int32


In [129]:
t1 = torch.tensor(10., dtype = bool)  # scalar 데이터, bool
print_attribute(t1, 't1')

[ Tensor t1's Attribute ]
- tensor.shape : torch.Size([])
- tensor.ndim : 0D
- tensor.dtype : torch.bool
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
True


In [130]:
t1 = torch.tensor([1, 2, 3], dtype = torch.int8)  # 1D 데이터
print_attribute(t1, 't1')

[ Tensor t1's Attribute ]
- tensor.shape : torch.Size([3])
- tensor.ndim : 1D
- tensor.dtype : torch.int8
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([1, 2, 3], dtype=torch.int8)


In [131]:
t1 = torch.tensor([[1, 2, 3]], dtype = torch.int8)  # 2D 데이터
print_attribute(t1, 't1')

[ Tensor t1's Attribute ]
- tensor.shape : torch.Size([1, 3])
- tensor.ndim : 2D
- tensor.dtype : torch.int8
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([[1, 2, 3]], dtype=torch.int8)


- Tensor 생성 (3) 특정 값으로 채운 텐서 => 0, 1 등의 값

In [132]:
# 0으로 채운 텐서
t1 = torch.zeros(5)
print_attribute(t1, 't1')

[ Tensor t1's Attribute ]
- tensor.shape : torch.Size([5])
- tensor.ndim : 1D
- tensor.dtype : torch.float32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([0., 0., 0., 0., 0.])


In [133]:
t1 = torch.zeros((5, 5), dtype = torch.int8)
print_attribute(t1, 't1')

[ Tensor t1's Attribute ]
- tensor.shape : torch.Size([5, 5])
- tensor.ndim : 2D
- tensor.dtype : torch.int8
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int8)


In [134]:
# 1로 채운 텐서
t1 = torch.ones((2, 4), dtype = torch.int8)
print_attribute(t1, 't1')

[ Tensor t1's Attribute ]
- tensor.shape : torch.Size([2, 4])
- tensor.ndim : 2D
- tensor.dtype : torch.int8
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int8)


In [135]:
# 이미 존재하는 텐서와 동일한 shape으로 잡고 값 채우기 => zeros_like(), ones_like()
img = torch.tensor([[2, 3, 4, 5, 6, 7,], [2, 3, 4, 5, 6, 7]])
img.shape

torch.Size([2, 6])

In [136]:
zero_img = torch.zeros_like(img)
zero_img

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])

In [137]:
one_img = torch.ones_like(img)
one_img

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])

In [138]:
full_img = torch.full_like(img, 7)
full_img

tensor([[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]])

In [139]:
# 대각선 방향으로 1채우기 => eye()
t1 = torch.eye(5)
t1

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

 - Tensor 생성 방법 (4) : 임의의 값으로 Tensor 생성 => torch.rand(), torch.randn(), torch.randint()

In [140]:
# 랜덤 초기값 설정
torch.manual_seed(12)

t5 = torch.rand(2, 3)
t6 = torch.randn(2, 3)
t7 = torch.randint(low = 1, high = 10, size = (2, 3))  # low <= ~ < high

In [141]:
print_attribute(t5, 't5')
print_attribute(t6, 't6')
print_attribute(t7, 't7')

[ Tensor t5's Attribute ]
- tensor.shape : torch.Size([2, 3])
- tensor.ndim : 2D
- tensor.dtype : torch.float32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])
[ Tensor t6's Attribute ]
- tensor.shape : torch.Size([2, 3])
- tensor.ndim : 2D
- tensor.dtype : torch.float32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([[ 1.5869,  1.1268, -1.2274],
        [-0.8216, -1.7861,  0.6167]])
[ Tensor t7's Attribute ]
- tensor.shape : torch.Size([2, 3])
- tensor.ndim : 2D
- tensor.dtype : torch.int64
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([[8, 4, 6],
        [2, 2, 2]])


 - Tensor 생성 방법 (5) : Ndarray 객체 활용 => torch.from_numpy(), torch.as_tensor(), tensor()

In [142]:
# 데이터 생성
import numpy as np

data = np.array([11, 22, 33])
print(data, type(data))

[11 22 33] <class 'numpy.ndarray'>


In [143]:
t1 = torch.from_numpy(data)
t1

tensor([11, 22, 33], dtype=torch.int32)

In [144]:
t2 = torch.as_tensor(data)
t2

tensor([11, 22, 33], dtype=torch.int32)

In [145]:
t3 = torch.tensor(data)
t3

tensor([11, 22, 33], dtype=torch.int32)

In [146]:
# ndarray 원소 변경
data[0] = 100

In [147]:
# from_numpy(), as_tensor() ==> 데이터 공유
# tensor() => 복사본 생성
print(data, t1, t2, t3, sep = '\n')

[100  22  33]
tensor([100,  22,  33], dtype=torch.int32)
tensor([100,  22,  33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)


- 브로드캐스팅 연산

In [148]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(f'm1.shape => {m1.shape}, m2.shape => {m2.shape}')

m3 = m1 + m2
print(f'm3.shape => {m3.shape})')
m3


m1.shape => torch.Size([1, 2]), m2.shape => torch.Size([1])
m3.shape => torch.Size([1, 2]))


tensor([[4., 5.]])

In [149]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(f'm1.shape => {m1.shape}, m2.shape => {m2.shape}')

m3 = m1 + m2
print(f'm3.shape => {m3.shape}')
m3

m1.shape => torch.Size([1, 2]), m2.shape => torch.Size([2, 1])
m3.shape => torch.Size([2, 2])


tensor([[4., 5.],
        [5., 6.]])

In [150]:
m3 = m1 * m2
m4 = m1.mul(m2)
print(f'm3.shape => {m3.shape}')
print(m3)
print(f'm4.shape => {m4.shape}')
print(m4)

m3.shape => torch.Size([2, 2])
tensor([[3., 6.],
        [4., 8.]])
m4.shape => torch.Size([2, 2])
tensor([[3., 6.],
        [4., 8.]])


In [151]:
# 원소 단위 연산 수행 메서드
m1.add(m2), m1.sub(m2), m1.mul(m2), m1.div(m2)

(tensor([[4., 5.],
         [5., 6.]]),
 tensor([[-2., -1.],
         [-3., -2.]]),
 tensor([[3., 6.],
         [4., 8.]]),
 tensor([[0.3333, 0.6667],
         [0.2500, 0.5000]]))