### Tensor shape 변경
- reshape(), view() : 원소 개수가 유지되고 기존의 텐서를 공유한다.

In [79]:
# 모듈 로딩
import torch

In [80]:
# 텐서 데이터 생성
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t1.shape, t1.ndim)

torch.Size([2, 3]) 2


In [81]:
# [2, 3] ===> [3, 2] 형태 변경 : 원소 동일 6개
t1.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [82]:
# [2, 3] ===> [6, 1] 형태 변경 : 원소 동일 6개
# 다음 결과는 같다.
t1.view(6, 1)
t1.view(-1, 1)  # -1 : 행 또는 열 개수 고정 후 나머지

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [83]:
# tensor.reshape()
t1.reshape(-1, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [84]:
# 원소 수 유지되어야 함!
# RuntimeError : shape '[-1, 7]' is invalid for input of size 6
# t1.reshape(-1, 7)

- 전치 : 열 <-> 형 변경

In [85]:
print(t1.shape)
t2 = t1.T
print(t2.shape, t2.is_contiguous)

torch.Size([2, 3])
torch.Size([3, 2]) <built-in method is_contiguous of Tensor object at 0x000002D382E364F0>


In [86]:
# RuntimeError : view size is not compatible with input tensor's size and stride
t2.view(-1, 6)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [ ]:
t2.reshape(-1, 6)

tensor([[1, 4, 2, 5, 3, 6]])

### 텐서 데이터의 메모리 저장 정보 즉 메타데이터
- 현재 저장 형태, 검색 방향 정보, 시작 정보

In [ ]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t1.shape, t1.ndim)
print(f't1.storage() => {t1.storage()}')
print(f't1.storage_offset() => {t1.storage_offset()}')
print(f't1.stride() => {t1.stride()}')
print(f't1.stride() => {t1.is_contiguous()}')

torch.Size([2, 3]) 2
t1.storage() =>  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t1.storage_offset() => 0
t1.stride() => (3, 1)
t1.stride() => True


In [ ]:
t2 = t1.view(-1, 2)
print(t2.shape, t2.ndim)
print(f't2.storage() => {t2.storage()}')
print(f't2.storage_offset() => {t2.storage_offset()}')
print(f't2.stride() => {t2.stride()}')
print(f't2.stride() => {t2.is_contiguous()}')

torch.Size([3, 2]) 2
t2.storage() =>  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t2.storage_offset() => 0
t2.stride() => (2, 1)
t2.stride() => True


### 차원 제거/추가
- tensor.squeeze() : 텐서에서 차원이 1인 것 제거
- tensor.unsqueeze(dim) : 텐서에 차원 1인 것 추가

In [ ]:
# 데이터 생성
t1 = torch.tensor([[1, 2,], [3, 4]])
t2 = torch.tensor([[1, 2, 3, 4]])
t3 = torch.tensor([[[1, 2, 3, 4]]])

In [ ]:
print(f't1 => {t1.shape} {t1.ndim}D')
print(f't2 => {t2.shape} {t2.ndim}D')
print(f't3 => {t3.shape} {t3.ndim}D')

t1 => torch.Size([2, 2]) 2D
t2 => torch.Size([1, 4]) 2D
t3 => torch.Size([1, 1, 4]) 3D


In [ ]:
t11 = t1.squeeze()
t22 = t2.squeeze()
t33 = t3.squeeze()
t44 = t3.squeeze(dim = 0)  # dim에 배정된 차원만 삭제 => 참고) (데이터수[0], 채널[1], 행[2], 열[3])
print(f't1 차원 축소 => {t11.shape} {t11.ndim}D')
print(f't2 차원 축소 => {t22.shape} {t22.ndim}D')
print(f't3 차원 축소 => {t33.shape} {t33.ndim}D')
print(f't3 차원 축소 => {t44.shape} {t44.ndim}D')

t1 차원 축소 => torch.Size([2, 3]) 2D
t2 차원 축소 => torch.Size([3, 2]) 2D
t3 차원 축소 => torch.Size([4]) 1D
t3 차원 축소 => torch.Size([1, 4]) 2D


In [ ]:
print(f't1 정보 => {t1.shape}, {t1.ndim}D, {t1.data_ptr()}, {t1.stride()}')

t1 정보 => torch.Size([2, 3]), 2D, 4661574637440, (3, 1)


In [87]:
# 원소/요소 수 변경 없이 1차원 증가 시키기 => torch.unsqueeze(dim)
t11 = t1.unsqueeze(dim = 0)
t22 = t2.unsqueeze(dim = -1)  # dim = 2와 동일

print(f't1 차원 추가 => {t11.shape}, {t11.ndim}D, {t11.data_ptr()}, {t11.stride()}')
print(f't2 차원 추가 => {t22.shape}, {t22.ndim}D, {t22.data_ptr()}, {t22.stride()}')

t1 차원 추가 => torch.Size([1, 2, 3]), 3D, 4661574637568, (6, 3, 1)
t2 차원 추가 => torch.Size([3, 2, 1]), 3D, 4661574637568, (1, 3, 1)


In [ ]:
# None => 차원 추가
t1.shape, t1[None].shape

(torch.Size([2, 2]), torch.Size([1, 2, 2]))

## Tensor 차원/형태 변경

In [ ]:
t1 = torch.tensor([[[1, 2], [11, 22], [44, 55]]])
print(f't1 => {t1.shape}, {t1.ndim}D')

t1 => torch.Size([1, 3, 2]), 3D


In [ ]:
# 2개의 차원을 변경하는 메서드
t2 = t1.transpose(0, 2)
print(f't2 => {t2.shape}, {t2.ndim}D')

t2 => torch.Size([2, 3, 1]), 3D


In [ ]:
# 모든 차원을 변경하는 메서드
t22 = t1.permute(1, 2, 0)
print(f't2 => {t22.shape}, {t22.ndim}D')

t2 => torch.Size([3, 2, 1]), 3D


In [88]:
# Tensor객체변수명.타입명()
lt = torch.LongTensor([1, 2, 3, 4])
print(lt.dtype, lt)       # int
print(lt.float().dtype)   # flaot 타입으로 형변환
print(lt.char().dtype)    # char 타입으로 형변환
print(lt.double().dtype)  # double 타입으로 형변환
print(lt.bool().dtype)    # bool 타입으로 형변환

torch.int64 tensor([1, 2, 3, 4])
torch.float32
torch.int8
torch.float64
torch.bool


In [90]:
# Tensor객체변수명.type(torch.xxx)
lt = torch.LongTensor([1, 2, 3, 4])
print(lt.dtype, lt)
print(lt.type(torch.float32))      # float 타입으로 형변환
print(lt.type(torch.int8))         # char 타입으로 형변환
print(lt.type(torch.double))       # double 타입으로 형변환
print(lt.type(torch.bool))         # bool 타입으로 형변환

torch.int64 tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 2, 3, 4], dtype=torch.int8)
tensor([1., 2., 3., 4.], dtype=torch.float64)
tensor([True, True, True, True])
