### 텐서 연결 & 결합

In [1]:
# 모듈 로딩
import torch

In [2]:
# 텐서 랜덤 고정
torch.manual_seed(12)

# 임의의 0. <= ~ < 1. 실수
X = torch.rand(2, 10)

# #임의의 정수 : low <= ~ < high
y = torch.randint(0, 2, (10,))
y2 = torch.randint(0, 2, (2, 10))

In [3]:
print(y2)
print(X)

tensor([[1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 0, 0, 0, 0]])
tensor([[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421, 0.7312,
         0.7224],
        [0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262, 0.9790, 0.8443, 0.1256,
         0.4456]])


In [4]:
print(f'x => {X.shape}, {X.ndim}D')
print(f'y => {y.shape}, {y.ndim}D')
print(f'y2 => {y2.shape}, {y2.ndim}D')

x => torch.Size([2, 10]), 2D
y => torch.Size([10]), 1D
y2 => torch.Size([2, 10]), 2D


In [5]:
# tensor 연결 cat([텐서1, 텐서2, ...])
xy1 = torch.cat([X, y2], dim = 0)
print(f'xy1 => {xy1.shape}, {xy1.ndim}D')

xy1 => torch.Size([4, 10]), 2D


In [6]:
# 행 단위로 최대값 및 최대값의 인덱스
max_value = xy1.max(dim = 1)[0]
max_index = xy1.max(dim = 1)[1]

max_value, max_index

(tensor([0.7312, 0.9790, 1.0000, 1.0000]), tensor([8, 6, 0, 2]))

In [7]:
# 열 단위로 최대값 및 최대값의 인덱스
max_value = xy1.max(dim = 0)[0]
max_index = xy1.max(dim = 0)[1]

max_value, max_index

(tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9790, 0.8443, 0.7312,
         0.7224]),
 tensor([2, 2, 3, 2, 2, 3, 1, 1, 0, 0]))

In [8]:
import pandas as pd
data = pd.DataFrame({'A' : [10, 11], 'B' : [20, 22], 'C' : [30, 33]})
data

A   B   C
0  10  20  30
1  11  22  33

In [9]:
data.max(), data.max(axis = 0)

(A    11
 B    22
 C    33
 dtype: int64,
 A    11
 B    22
 C    33
 dtype: int64)

In [10]:
data.max(axis = 1)

0    30
1    33
dtype: int64

In [11]:
# tensor 연결 stack([텐서1, 텐서2, ...]) : 쌓기 + 연산수행
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

# 아래 두 결과는 같다.
torch.stack([x, y, z])
torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])